[package]
name = "splitbin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
clap-num = "1.2.0"
path-absolutize = "3.1.1"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
